In [1]:
#transpose a vector or matrix
import numpy as np
vector = np.array([1,2,3,4,5,6])

In [2]:
#create a matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [3]:
#transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
#Create A Sparse Matrix
from scipy import sparse

In [5]:
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

In [6]:
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [7]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

In [8]:
#Selecting Elements In An Array
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

In [9]:
# Select second element
vector[1]

2

In [10]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [11]:
# Select second row, second column
matrix[1,1]

5

In [12]:
#Create Tensor

# Create matrix
tensor = np.array([
                    [[[1, 1], [1, 1]], [[2, 2], [2, 2]]],
                    [[[3, 3], [3, 3]], [[4, 4], [4, 4]]]
                  ])

In [13]:
# Select second element of each of the three dimensions
tensor[1,1,1]

array([4, 4])

In [14]:
#create matrix
matrix = np.array([[1 , 4],
                  [2  , 5]])

array([[1, 4],
       [2, 5]])

In [15]:
#Reshape an array

#create a 4*3 matrix

matrix = np.array([[4 , 2 , 6],
                   [5 , 2 , 7],
                   [5 , 3 , 8],
                   [3 , 6 , 2]])

In [16]:
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[4, 2, 6, 5, 2, 7],
       [5, 3, 8, 3, 6, 2]])

In [17]:
#Converting A Dictionary Into A Matrix

# Load library
from sklearn.feature_extraction import DictVectorizer

In [18]:
# Our dictionary of data
data_dict = [{'Red': 2, 'Blue': 4},
             {'Red': 4, 'Blue': 3},
             {'Red': 1, 'Yellow': 2},
             {'Red': 2, 'Yellow': 2}]

In [19]:
# Create DictVectorizer object
dictvectorizer = DictVectorizer(sparse=False)

# Convert dictionary into feature matrix
features = dictvectorizer.fit_transform(data_dict)

# View feature matrix
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [22]:
# View feature matrix column names
dictvectorizer.get_feature_names()

['Blue', 'Red', 'Yellow']

In [23]:
#Invert A Matrix

# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

In [24]:
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [25]:
#Calculate The Trace Of A Matrix

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [26]:
# Calculate the tracre of the matrix
matrix.diagonal().sum()

15

In [27]:
#Getting The Diagonal Of A Matrix

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [28]:
# Return diagonal elements
matrix.diagonal()

array([1, 5, 9])

In [29]:
# Calculate the tracre of the matrix
matrix.diagonal().sum()

15

In [30]:
#Calculate The Determinant Of A Matrix

# Return determinant of matrix
np.linalg.det(matrix)

-9.51619735392994e-16

In [31]:
#Flatten A Matrix

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#Calculate The Average, Variance, And Standard Deviation

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [33]:
# Return mean
np.mean(matrix)

5.0

In [34]:
# Return variance
np.var(matrix)

6.666666666666667

In [35]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [36]:
#Find Rank Of Matrix

# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [37]:
#Calculate Dot Product Of Two Vectors

In [38]:
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [39]:
# Calculate dot product
np.dot(vector_a, vector_b)

32

In [40]:
# Calculate dot product (ATTERNATE METHOD)
vector_a @ vector_b

32

In [41]:
#Find The Maximum And Minimum

In [42]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [43]:
# Return maximum element
np.max(matrix)

9

In [44]:
# Return minimum element
np.min(matrix)

1

In [45]:
# Find the maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [46]:
# Find the maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

In [47]:
#Describe An Array

In [48]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [49]:
# View number of rows and columns
matrix.shape

(3, 4)

In [50]:
# View number of elements (rows * columns)
matrix.size

12

In [51]:
# View number of dimensions
matrix.ndim

2

In [52]:
#Apply Operations To Elements

In [53]:
#Create Vectorized Function

In [54]:
# Create a function that adds 100 to something
add_100 = lambda i: i + 100

# Create a vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [55]:
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

In [56]:
#Create A Vector

# Create a vector as a row
vector_row = np.array([1, 2, 3])

In [57]:
# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [58]:
#Adding And Subtracting Matrices

In [59]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

In [60]:
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [61]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])